spec:
  template:
    metadata:
      annotations:
        # This tells Istio: "Add this file to your default ROOTCA bundle"
        # This makes ISTIO_MUTUAL work automatically!
        proxy.istio.io/config: |
          caCertificatesPem:
          - "/var/run/secrets/spire-bundle/root-cert.pem"
    spec:
      containers:
      - name: istio-proxy
        volumeMounts:
        - name: spire-bundle
          mountPath: "/var/run/secrets/spire-bundle"
          readOnly: true
      volumes:
      - name: spire-bundle
        configMap:
          name: spire-bundle
